defaults: &defaults
  working_directory: ~/repo
  docker:
    - image:  circleci/node:8-browsers-legacy

version: 2

releases: &releases
  filters:
    tags:
      only: /v[0-9]+(\.[0-9]+)*/
    branches:
      ignore: /.*/

jobs:
  checkout:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Install external tools
          command: pip3 install cfn-lint

      - run:
          name: Install dependecies
          command: make install

      - persist_to_workspace:
          root: ~/
          paths:
            - '*'
            - '*.*'

  lint:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Run code analyzis
          command: make lint-all

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Run tests
          command: make unit-test

  publish:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Publish to Serverless Application repository
          command: make publish

workflows:
  version: 2

  build:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - lint:
          requires:
            - checkout
  release:
    jobs:
      - checkout:
          <<: *releases
      - test:
          <<: *releases
          requires:
            - checkout
      - lint:
          <<: *releases
          requires:
            - checkout
      - publish:
          <<: *releases
          requires:
            - test
            - lint
