name: lambda

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: v8.15.0
      - name: install
        run: make install
      - name: lint
        run: make lint-all
      - name: tests
        run: make unit-test
      - name: build
        run: make build

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: build
    steps:
      - uses: actions/checkout@v1

      - name: install
        run: make install

      - name: build
        run: make build

      - name: deploy
        uses: r0zar/sam-deploy-action@v1.0
        env:
          TEMPLATE: ./sam/template.yaml
          AWS_STACK_NAME: from-ses-to-s3
          AWS_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEPLOY_BUCKET: sam-deploy-packages
          PARAMETER_OVERRIDES: StorageBucket=invoice-storage-oleksii
